image: node:18
stages:
  - lint
  - test


lint:
  stage: lint
  script:
    - npm install
    - npx eslint src/*/*.js -f
    - npx htmlhint src/*/*.html -f
    - npx stylelint src/*/* -f
  artifacts:
        when: always
        paths:
            - lint.json
        reports:
            codequality: lint.json

test:
  script:
    - npm install
    - npm test
  artifacts:
      when: always
      reports:
          junit:
              - test-results.xml
      paths:
      - test-results.xml

build:
  image: docker
  needs:
    - test
  script:
    - docker build -t web-test .