image: node:latest

lint:
  script:
    - cd BinaryWizards-MobileApp/
    - npm install
    - npx eslint . --ext .js,.jsx,.ts,.tsx -f json -o lint.json
  artifacts:
    when: always
    paths:
      - BinaryWizards-MobileApp//lint.json
  allow_failure: true

