import { StyleSheet } from "react-native";

export default styles = StyleSheet.create({
    container: {
      flex: 1,
      width: '100%',
      alignItems: 'center',
      backgroundColor: '#F7F8FA',
      paddingTop: 20,
    },
    buttonContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      width: '90%',
      marginVertical: 20,
    },
    button: {
      backgroundColor: '#ffffff',
      borderWidth: 1,
      borderColor: '#DDDDDD',
      borderRadius: 10,
      paddingVertical: 12,
      paddingHorizontal: 20,
      textAlign: 'center',
      fontSize: 16,
      fontWeight: '600',
      color: '#666',
      transition: '0.3s all',
    },
    buttonSelected: {
      backgroundColor: '#3552B0',
      borderWidth: 1,
      borderColor: '#3552B0',
      borderRadius: 10,
      paddingVertical: 12,
      paddingHorizontal: 20,
      textAlign: 'center',
      fontSize: 16,
      fontWeight: '600',
      color: '#ffffff',
      shadowColor: '#3552B0',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      elevation: 3,
      transition: '0.3s all',
    },
  });